### ISSUE TITLE
The link to the IOS beta doesn't seem to work

### ISSUE THREAD

**Issue by apprehensivetarget** [cgtinker/ArRetargeter#1]
The link to the IOS beta doesn't seem to work, when i try and open it on my phone, it tells me the link is invalid. How can i build this from source, as this project seems very interesting, and i'd love to try it

**Comment by apprehensivetarget** [comment]
Nevermind, My phone was bugging, it works now

**Comment by cgtinker** [comment]
Oh hey,Great it worked. I already was wondering, as I'm currently preforming a build update (also renaming the app) so there could be some downtime soon.However, have fun testing!Regards :)On 8 Mar 2021 20:18, apprehensivetarget <notifications@github.com> wrote:
Nevermind, My phone was bugging, it works now

**Comment by apprehensivetarget** [comment]
Its an amazing app now that ive tried it, a huge time saver. Thanks a lot.
