### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [cgtinker/ArRetargeter#10]
...

**Comment by cgtinker** [comment]
Whats your device?

**Comment by Uniersr** [comment]
> Whats your device?

Moto G5 but its android version is oficially upgraded to 8.1.0

**Comment by cgtinker** [comment]
It doesn't seem to be in the [supported devices](https://developers.google.com/ar/devices) list by ArCore.
ArCore support is sadly required. I'll recheck my build setting soon, actually it shouldn't be available for your device...

sorry :(
