### ISSUE TITLE
make available on F-Droid?

### ISSUE THREAD

**Issue by ghost** [cgtinker/ArRetargeter#11]
Can / Will you make the app available on F-Droid and continue the free & open source basic idea of Blender? :)
The license would remain, but Google services are to be avoided... I guess you have several Google dependencies?

**Comment by cgtinker** [comment]
ArCore is by google (while being open-source).
Actually I misread at first. Probably I can publish a version at F-Droid, I'll look into it.

Thanks for the suggestion ;)
