### ISSUE TITLE
record audio?

### ISSUE THREAD

**Issue by devriesewouter89** [cgtinker/ArRetargeter#14]
Hi
what would be the best way to record audio via the app? Without it, you're loosing the sync and have to do manual work to sync facial expressions with audio tracks.
(I didn't find it in the app, perhaps I've been looking at it wrongly?)

**Comment by cgtinker** [comment]
Sorry for answering that late - there is no option to record audio and probably won't be in the near future. It kinda goes hand in hand with the video recorder and at the time it looks like I have to write a new one basically from scratch... and that's is a long term project. Will see =)
