### ISSUE TITLE
IOS - Face tracking data doesn't save - all json files are empty

### ISSUE THREAD

**Issue by EverythingerTruten** [cgtinker/ArRetargeter#15]
Hello, I just installed the app from the App Store on an Iphone 8 Plus and recorded some test face tracking recordings, but when I tried to preview them this error message popped up:

> operation failed
> cannot preview data - it's probably corrupted. the .json may contains a closing a closing parenthesis error.
> consider to record again. if you can reproduce the error please message me

This happened every time I tried to use the face tracking feature. Also when I looked at the screen while recording, the face wireframe didn't appear.

When I tried to open the files on my computer none of them contained any information, except for the first line:

All *_face.json* files:
`{"meshDataList":[`

All *_face_mesh.json* files:
`{"meshGeometry":[`

All *_f-pose.json* files:
`{"facePoseList":[`

Thanks for any help, this app seems great for my workflow but right now I can't use it.

**Comment by cgtinker** [comment]
Hey there,

Face tracking is not available pre iPhone 10. Wondering why you can access it (thought I fixed that in the past..).

Best regards

**Comment by EverythingerTruten** [comment]
> Hey there,Face tracking is not available pre iPhone 10. Wondering why you can access it (thought I fixed that in the past..).Best regards,DenysOn 25 Feb 2023 18:28, EverythingerTruten ***@***.***> wrote: Hello, I just installed the app from the App Store on an Iphone 8 Plus and recorded some test face tracking recordings, but when I tried to preview them this error message popped up: operation failed cannot preview data - it's probably corrupted. the .json may contains a closing a closing parenthesis error. consider to record again. if you can reproduce the error please message me This happened every time I tried to use the face tracking feature. Also when I looked at the screen while recording, the face wireframe didn't appear. When I tried to open the files on my computer none of them contained any information, except for the first line: All _face.json files: {"meshDataList":[ All _face_mesh.json files: {"meshGeometry":[ All _f-pose.json files: {"facePoseList":[ Thanks for any help, this app seems great for my workflow but right now I can't use it. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
